// <auto-generated />
using System;
using ArchAutomate.Data;
using ArchAutomate.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchAutomate.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420130610_AddProjectIfcPath")]
    partial class AddProjectIfcPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_status", new[] { "draft", "in_progress", "submitted_to_council", "approved", "rejected", "revised" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "rejection_category", new[] { "zoning", "building_lines", "parking", "accessibility", "structural_documentation", "fire_compliance", "drainage", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "rejection_status", new[] { "open", "in_progress", "resolved", "disputed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "stakeholder_role", new[] { "architect", "client", "structural_engineer", "electrical_engineer", "plumbing_engineer", "quantity_surveyor", "council_officer", "contractor", "other" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchAutomate.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Erf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("erf");

                    b.Property<string>("IfcPath")
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<double>("SiteAreaM2")
                        .HasColumnType("double precision")
                        .HasColumnName("site_area_m2");

                    b.Property<ProjectStatus>("Status")
                        .HasColumnType("project_status")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZoningScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zoning_scheme");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ArchAutomate.Data.Entities.RejectionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<RejectionCategory>("Category")
                        .HasColumnType("rejection_category")
                        .HasColumnName("category");

                    b.Property<string>("ClauseReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clause_reference");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<string>("ParsedAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parsed_action");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("SourceDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_document");

                    b.Property<RejectionStatus>("Status")
                        .HasColumnType("rejection_status")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("rejection_comments", (string)null);
                });

            modelBuilder.Entity("ArchAutomate.Data.Entities.Stakeholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisation");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<StakeholderRole>("Role")
                        .HasColumnType("stakeholder_role")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("stakeholders", (string)null);
                });

            modelBuilder.Entity("ArchAutomate.Data.Entities.RejectionComment", b =>
                {
                    b.HasOne("ArchAutomate.Data.Entities.Project", "Project")
                        .WithMany("RejectionComments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ArchAutomate.Data.Entities.Stakeholder", b =>
                {
                    b.HasOne("ArchAutomate.Data.Entities.Project", "Project")
                        .WithMany("Stakeholders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ArchAutomate.Data.Entities.Project", b =>
                {
                    b.Navigation("RejectionComments");

                    b.Navigation("Stakeholders");
                });
#pragma warning restore 612, 618
        }
    }
}
