/**
 * exportService.js
 * Pure client-side PDF (jsPDF + jspdf-autotable) and Excel (SheetJS) export engine.
 * All functions accept plain data objects and return blobs or trigger downloads.
 *
 * Exports:
 *   exportPdf(payload)  → downloads a council-ready PDF
 *   exportExcel(payload) → downloads a QS-ready .xlsx workbook
 */

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'

// ── Palette ──────────────────────────────────────────────────────────────────
const BRAND = [30, 64, 175]   // indigo-800 in RGB
const DARK  = [15, 23, 42]    // slate-900
const LIGHT = [241, 245, 249] // slate-100

// ── Helpers ───────────────────────────────────────────────────────────────────

function today() {
  return new Date().toLocaleDateString('en-ZA', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
}

function pct(v) {
  return v != null ? `${Number(v).toFixed(1)}%` : '—'
}
function num(v, dp = 2) {
  return v != null ? Number(v).toFixed(dp) : '—'
}
function passFailBadge(pass) {
  return pass ? '✓ PASS' : '✗ FAIL'
}

// ── PDF helpers ───────────────────────────────────────────────────────────────

/**
 * Draws the standard page header (logo placeholder, project name, date).
 * Returns the Y position after the header.
 */
function drawHeader(doc, projectName, subtitle) {
  const W = doc.internal.pageSize.getWidth()
  // Navy header bar
  doc.setFillColor(...BRAND)
  doc.rect(0, 0, W, 28, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('ArchAutomate', 12, 11)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('South African Architect Post-Design Portal', 12, 17)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(projectName, W / 2, 11, { align: 'center' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(subtitle, W / 2, 17, { align: 'center' })

  doc.setFontSize(8)
  doc.text(today(), W - 12, 11, { align: 'right' })
  doc.text('Confidential', W - 12, 17, { align: 'right' })

  doc.setTextColor(...DARK)
  return 36
}

/**
 * Draws a section heading.
 */
function drawSection(doc, title, y) {
  const W = doc.internal.pageSize.getWidth()
  doc.setFillColor(...LIGHT)
  doc.rect(10, y, W - 20, 7, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...BRAND)
  doc.text(title.toUpperCase(), 13, y + 5)
  doc.setTextColor(...DARK)
  return y + 10
}

/**
 * Draws a two-column key/value info block.
 */
function drawInfoGrid(doc, rows, y) {
  const colW = 85
  const rowH = 6
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')

  rows.forEach(([label, value], i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const x = 12 + col * colW
    const yy = y + row * rowH
    doc.setFont('helvetica', 'bold')
    doc.text(label + ':', x, yy)
    doc.setFont('helvetica', 'normal')
    doc.text(String(value ?? '—'), x + 38, yy)
  })

  return y + Math.ceil(rows.length / 2) * rowH + 4
}

/**
 * Adds a standard page footer to every page.
 */
function addFooters(doc, projectName) {
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const W = doc.internal.pageSize.getWidth()
    const H = doc.internal.pageSize.getHeight()
    doc.setFontSize(7)
    doc.setTextColor(150)
    doc.text(`${projectName} — Generated by ArchAutomate on ${today()}`, 12, H - 6)
    doc.text(`Page ${i} of ${pageCount}`, W - 12, H - 6, { align: 'right' })
    doc.setDrawColor(200)
    doc.line(10, H - 9, W - 10, H - 9)
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// PDF EXPORT
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Generates and downloads a council-ready PDF report.
 *
 * @param {Object} payload
 * @param {Object}  payload.project         - { name, municipality, erfNumber, siteAreaM2, zoningScheme, … }
 * @param {Object}  [payload.zoning]        - { result, params, scheme } from ZoningView
 * @param {Object}  [payload.energy]        - { result, params } from energy compliance
 * @param {Object}  [payload.schedule]      - { doors: [], windows: [] }
 * @param {Object}  [payload.tally]         - { items: [], lightingCount, … }
 * @param {Object}  [payload.spec]          - CompiledSpec { sections: [] }
 */
export function exportPdf(payload) {
  const { project, zoning, energy, schedule, tally, spec } = payload
  const projectName = project?.name ?? 'Unnamed Project'

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  doc.setFont('helvetica')
  let y = 0

  // ── Cover / Project Summary ────────────────────────────────────────────────
  y = drawHeader(doc, projectName, 'Council Submission Report')
  y = drawSection(doc, 'Project Information', y)
  y = drawInfoGrid(doc, [
    ['Project Name', project?.name],
    ['Municipality',  project?.municipality ?? '—'],
    ['Erf Number',    project?.erfNumber ?? '—'],
    ['Zoning Scheme', project?.zoningScheme ?? '—'],
    ['Site Area',     project?.siteAreaM2 ? `${project.siteAreaM2} m²` : '—'],
    ['Report Date',   today()],
  ], y)

  // ── Zoning Compliance ──────────────────────────────────────────────────────
  if (zoning?.result) {
    y += 4
    if (y > 250) { doc.addPage(); y = drawHeader(doc, projectName, 'Zoning Compliance') }
    y = drawSection(doc, 'Municipal Zoning Compliance', y)

    const r = zoning.result
    const p = zoning.params ?? {}
    const s = zoning.scheme ?? {}

    // Summary pass/fail
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    const overallPass = r.isCompliant !== false
    doc.setTextColor(...(overallPass ? [22, 163, 74] : [220, 38, 38]))
    doc.text(overallPass ? '✓  OVERALL: COMPLIANT' : '✗  OVERALL: NON-COMPLIANT', 12, y)
    doc.setTextColor(...DARK)
    y += 8

    // Build table from checks array (each has rule, description, providedValue, requiredValue, unit, passed)
    const checkRows = (r.checks ?? []).map((c) => [
      c.description ?? c.rule ?? '',
      c.providedValue != null ? `${Number(c.providedValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
      c.requiredValue != null ? `${Number(c.requiredValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
      passFailBadge(c.passed),
    ])

    // Fallback: if no checks but we have params+scheme, build rows manually
    const tableRows = checkRows.length ? checkRows : [
      ['Coverage %',    pct(p.footprintM2 && p.siteAreaM2 ? (p.footprintM2 / p.siteAreaM2) * 100 : null),
                        pct(s.maxCoveragePercent), '—'],
      ['FAR', num(p.proposedGfaM2 && p.siteAreaM2 ? p.proposedGfaM2 / p.siteAreaM2 : null, 3),
              num(s.maxFar, 1), '—'],
    ]

    autoTable(doc, {
      startY: y,
      head: [['Parameter', 'Proposed', 'Permitted / Min', 'Status']],
      body: tableRows,
      headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 3: { halign: 'center' } },
      didParseCell: (data) => {
        if (data.column.index === 3 && data.section === 'body') {
          const txt = data.cell.text[0] ?? ''
          data.cell.styles.textColor = txt.startsWith('✓') ? [22, 163, 74] : [220, 38, 38]
          data.cell.styles.fontStyle = 'bold'
        }
      },
    })
    y = doc.lastAutoTable.finalY + 6

    if (r.violations?.length) {
      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.text('Non-conformances:', 12, y); y += 5
      doc.setFont('helvetica', 'normal')
      r.violations.forEach((v) => {
        const msg = typeof v === 'string' ? v : (v.message ?? JSON.stringify(v))
        doc.text(`• ${msg}`, 14, y); y += 5
        if (y > 270) { doc.addPage(); y = 20 }
      })
    }
  }

  // ── Energy Compliance (SANS 10400-XA) ──────────────────────────────────────
  if (energy?.result) {
    y += 4
    if (y > 230) { doc.addPage(); y = drawHeader(doc, projectName, 'Energy Compliance') }
    y = drawSection(doc, 'SANS 10400-XA Energy Compliance', y)

    const er = energy.result
    const ep = energy.params ?? {}

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...(er.isCompliant ? [22, 163, 74] : [220, 38, 38]))
    doc.text(er.isCompliant ? '✓  ENERGY: COMPLIANT' : '✗  ENERGY: NON-COMPLIANT', 12, y)
    doc.setTextColor(...DARK)
    y += 8

    autoTable(doc, {
      startY: y,
      head: [['Check', 'Value', 'Limit', 'Status']],
      body: (er.checks ?? []).map((c) => [
        c.description ?? c.rule ?? '',
        c.providedValue != null ? Number(c.providedValue).toFixed(2) + ' ' + (c.unit ?? '') : '—',
        c.requiredValue != null ? Number(c.requiredValue).toFixed(2) + ' ' + (c.unit ?? '') : '—',
        passFailBadge(c.passed),
      ]),
      headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 3: { halign: 'center' } },
      didParseCell: (data) => {
        if (data.column.index === 3 && data.section === 'body') {
          const txt = data.cell.text[0] ?? ''
          data.cell.styles.textColor = txt.startsWith('✓') ? [22, 163, 74] : [220, 38, 38]
          data.cell.styles.fontStyle = 'bold'
        }
      },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Door Schedule ──────────────────────────────────────────────────────────
  const doors = schedule?.doors ?? []
  if (doors.length) {
    if (y > 220) { doc.addPage(); y = drawHeader(doc, projectName, 'Door Schedule') }
    else y += 4
    y = drawSection(doc, `Door Schedule (${doors.length} items)`, y)

    autoTable(doc, {
      startY: y,
      head: [['Mark', 'Name / Type', 'Width (mm)', 'Height (mm)', 'Area (m²)', 'Level']],
      body: doors.map((d) => [
        d.mark, d.name || d.type || '—',
        d.widthMm ?? '—', d.heightMm ?? '—',
        d.areaM2 != null ? Number(d.areaM2).toFixed(2) : '—',
        d.level ?? '—',
      ]),
      headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8 },
      bodyStyles: { fontSize: 7.5 },
      alternateRowStyles: { fillColor: LIGHT },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Window Schedule ────────────────────────────────────────────────────────
  const windows = schedule?.windows ?? []
  if (windows.length) {
    if (y > 220) { doc.addPage(); y = drawHeader(doc, projectName, 'Window Schedule') }
    else y += 4
    y = drawSection(doc, `Window Schedule (${windows.length} items)`, y)

    autoTable(doc, {
      startY: y,
      head: [['Mark', 'Name / Type', 'Width (mm)', 'Height (mm)', 'Area (m²)', 'Level']],
      body: windows.map((w) => [
        w.mark, w.name || w.type || '—',
        w.widthMm ?? '—', w.heightMm ?? '—',
        w.areaM2 != null ? Number(w.areaM2).toFixed(2) : '—',
        w.level ?? '—',
      ]),
      headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8 },
      bodyStyles: { fontSize: 7.5 },
      alternateRowStyles: { fillColor: LIGHT },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Fixture Tally / BOQ ────────────────────────────────────────────────────
  const tallyItems = tally?.items ?? []
  if (tallyItems.length) {
    doc.addPage()
    y = drawHeader(doc, projectName, 'Fixture Tally — Bill of Quantities')
    y = drawSection(doc, `Fixture & MEP Tally (${tallyItems.length} items)`, y)

    // Summary counts
    y = drawInfoGrid(doc, [
      ['Lighting',    tally.lightingCount ?? 0],
      ['Electrical',  tally.electricalCount ?? 0],
      ['Sanitary',    tally.sanitaryCount ?? 0],
      ['HVAC',        tally.hvacCount ?? 0],
      ['Fire Safety', tally.fireCount ?? 0],
      ['Other',       tally.otherCount ?? 0],
    ], y)

    autoTable(doc, {
      startY: y,
      head: [['Category', 'IFC Type', 'Mark', 'Name', 'Level']],
      body: tallyItems.slice(0, 800).map((i) => [
        i.category, i.ifcType, i.mark, i.name || '—', i.level ?? '—',
      ]),
      headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8 },
      bodyStyles: { fontSize: 7 },
      alternateRowStyles: { fillColor: LIGHT },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Specification Clauses ──────────────────────────────────────────────────
  const sections = spec?.sections ?? []
  if (sections.length) {
    doc.addPage()
    y = drawHeader(doc, projectName, 'Construction Specification')

    sections.forEach((sec) => {
      if (!sec.clauses?.length) return
      if (y > 240) { doc.addPage(); y = drawHeader(doc, projectName, 'Construction Specification') }
      y = drawSection(doc, sec.name, y)
      sec.clauses.forEach((clause, i) => {
        if (y > 255) { doc.addPage(); y = 20 }
        doc.setFontSize(8)
        doc.setFont('helvetica', 'bold')
        doc.text(`${i + 1}.  ${clause.heading}`, 12, y)
        doc.setFont('helvetica', 'italic')
        doc.setTextColor(...BRAND)
        doc.text(clause.reference ?? '', doc.internal.pageSize.getWidth() - 12, y, { align: 'right' })
        doc.setTextColor(...DARK)
        y += 5
        doc.setFont('helvetica', 'normal')
        const lines = doc.splitTextToSize(clause.text ?? '', doc.internal.pageSize.getWidth() - 24)
        doc.text(lines, 14, y)
        y += lines.length * 4.2 + 4
      })
    })
  }

  addFooters(doc, projectName)

  const filename = `${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_Council_Report_${new Date().toISOString().slice(0, 10)}.pdf`
  doc.save(filename)
}

// ══════════════════════════════════════════════════════════════════════════════
// EXCEL EXPORT
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Generates and downloads a QS-ready Excel workbook (.xlsx).
 * Each data domain gets its own worksheet tab.
 *
 * @param {Object} payload  Same shape as exportPdf()
 */
export function exportExcel(payload) {
  const { project, zoning, energy, schedule, tally, spec } = payload
  const projectName = project?.name ?? 'Project'
  const wb = XLSX.utils.book_new()

  // ── Summary sheet ──────────────────────────────────────────────────────────
  const summaryRows = [
    ['ARCHAUTOMATE — PROJECT EXPORT'],
    [],
    ['Project Name', project?.name ?? '—'],
    ['Municipality',  project?.municipality ?? '—'],
    ['Erf Number',    project?.erfNumber ?? '—'],
    ['Zoning Scheme', project?.zoningScheme ?? '—'],
    ['Site Area (m²)', project?.siteAreaM2 ?? '—'],
    ['Export Date',   today()],
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows)
  wsSummary['!cols'] = [{ wch: 22 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Project Summary')

  // ── Zoning sheet ──────────────────────────────────────────────────────────
  if (zoning?.result || zoning?.params) {
    const r = zoning.result ?? {}
    const p = zoning.params ?? {}
    const s = zoning.scheme ?? {}
    const zoningRows = [
      ['Municipal Zoning Compliance'],
      ['Zoning Designation', s.name ?? project?.zoningScheme ?? '—'],
      [],
      ['Parameter', 'Proposed', 'Permitted / Min', 'Status'],
      ...(r.checks ?? []).map((c) => [
        c.description ?? c.rule ?? '',
        c.providedValue != null ? `${Number(c.providedValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
        c.requiredValue != null ? `${Number(c.requiredValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
        c.passed ? 'PASS' : 'FAIL',
      ]),
      [],
      ['Overall Compliance', r.isCompliant != null ? (r.isCompliant ? 'COMPLIANT' : 'NON-COMPLIANT') : '—'],
      [],
      ['Violations / Non-conformances'],
      ...(r.violations ?? []).map((v) => [typeof v === 'string' ? v : (v.message ?? '')]),
    ]
    const wsZoning = XLSX.utils.aoa_to_sheet(zoningRows)
    wsZoning['!cols'] = [{ wch: 24 }, { wch: 16 }, { wch: 14 }, { wch: 14 }]
    XLSX.utils.book_append_sheet(wb, wsZoning, 'Zoning Compliance')
  }

  // ── Energy sheet ───────────────────────────────────────────────────────────
  if (energy?.result) {
    const er = energy.result
    const ep = energy.params ?? {}
    const energyRows = [
      ['SANS 10400-XA Energy Compliance'],
      [],
      ['Parameter', 'Value', 'Limit', 'Status'],
      ...(er.checks ?? []).map((c) => [
        c.description ?? c.rule ?? '',
        c.providedValue != null ? `${Number(c.providedValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
        c.requiredValue != null ? `${Number(c.requiredValue).toFixed(2)} ${c.unit ?? ''}`.trim() : '—',
        c.passed ? 'PASS' : 'FAIL',
      ]),
      [],
      ['Overall', '', '', er.isCompliant ? 'COMPLIANT' : 'NON-COMPLIANT'],
      [],
      ['Climate Zone', ep?.climaticZone ?? er.climateZone ?? '—'],
      ['Energy Rating', er.energyRating ?? '—'],
      ['Window-to-Wall Ratio (%)', er.windowToWallRatioPercent != null ? pct(er.windowToWallRatioPercent) : '—'],
    ]
    const wsEnergy = XLSX.utils.aoa_to_sheet(energyRows)
    wsEnergy['!cols'] = [{ wch: 32 }, { wch: 16 }, { wch: 16 }, { wch: 14 }]
    XLSX.utils.book_append_sheet(wb, wsEnergy, 'Energy (XA)')
  }

  // ── Door Schedule sheet ────────────────────────────────────────────────────
  const doors = schedule?.doors ?? []
  if (doors.length) {
    const doorRows = [
      ['Door Schedule', '', '', '', '', ''],
      ['Mark', 'Name', 'Type', 'Width (mm)', 'Height (mm)', 'Area (m²)', 'Level'],
      ...doors.map((d) => [
        d.mark, d.name ?? '', d.type ?? '',
        d.widthMm ?? '', d.heightMm ?? '',
        d.areaM2 != null ? Number(d.areaM2).toFixed(3) : '',
        d.level ?? '',
      ]),
    ]
    const wsDoors = XLSX.utils.aoa_to_sheet(doorRows)
    wsDoors['!cols'] = [{ wch: 10 }, { wch: 20 }, { wch: 16 }, { wch: 12 }, { wch: 13 }, { wch: 10 }, { wch: 14 }]
    XLSX.utils.book_append_sheet(wb, wsDoors, 'Doors')
  }

  // ── Window Schedule sheet ──────────────────────────────────────────────────
  const windows = schedule?.windows ?? []
  if (windows.length) {
    const winRows = [
      ['Window Schedule', '', '', '', '', ''],
      ['Mark', 'Name', 'Type', 'Width (mm)', 'Height (mm)', 'Area (m²)', 'Level'],
      ...windows.map((w) => [
        w.mark, w.name ?? '', w.type ?? '',
        w.widthMm ?? '', w.heightMm ?? '',
        w.areaM2 != null ? Number(w.areaM2).toFixed(3) : '',
        w.level ?? '',
      ]),
    ]
    const wsWin = XLSX.utils.aoa_to_sheet(winRows)
    wsWin['!cols'] = [{ wch: 10 }, { wch: 20 }, { wch: 16 }, { wch: 12 }, { wch: 13 }, { wch: 10 }, { wch: 14 }]
    XLSX.utils.book_append_sheet(wb, wsWin, 'Windows')
  }

  // ── Fixture Tally / BOQ sheet ──────────────────────────────────────────────
  const tallyItems = tally?.items ?? []
  if (tallyItems.length) {
    const tallyRows = [
      ['Fixture Tally — Bill of Quantities (BOQ)'],
      [],
      ['Category Summary'],
      ['Lighting', tally?.lightingCount ?? 0],
      ['Electrical', tally?.electricalCount ?? 0],
      ['Sanitary', tally?.sanitaryCount ?? 0],
      ['HVAC', tally?.hvacCount ?? 0],
      ['Fire Safety', tally?.fireCount ?? 0],
      ['Other', tally?.otherCount ?? 0],
      ['TOTAL', tally?.totalCount ?? tallyItems.length],
      [],
      ['Category', 'IFC Type', 'Mark', 'Name', 'Level'],
      ...tallyItems.map((i) => [
        i.category, i.ifcType, i.mark, i.name ?? '', i.level ?? '',
      ]),
    ]
    const wsTally = XLSX.utils.aoa_to_sheet(tallyRows)
    wsTally['!cols'] = [{ wch: 14 }, { wch: 18 }, { wch: 12 }, { wch: 28 }, { wch: 18 }]
    XLSX.utils.book_append_sheet(wb, wsTally, 'Fixture BOQ')
  }

  // ── Specification sheet ────────────────────────────────────────────────────
  const sections = spec?.sections ?? []
  if (sections.length) {
    const specRows = [['Construction Specification'], []]
    sections.forEach((sec) => {
      specRows.push([sec.name.toUpperCase()])
      specRows.push(['#', 'Clause Heading', 'Specification Text', 'SANS Reference'])
      sec.clauses.forEach((c, i) => {
        specRows.push([i + 1, c.heading, c.text, c.reference])
      })
      specRows.push([])
    })
    const wsSpec = XLSX.utils.aoa_to_sheet(specRows)
    wsSpec['!cols'] = [{ wch: 4 }, { wch: 28 }, { wch: 80 }, { wch: 30 }]
    XLSX.utils.book_append_sheet(wb, wsSpec, 'Specification')
  }

  const filename = `${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_QS_Export_${new Date().toISOString().slice(0, 10)}.xlsx`
  XLSX.writeFile(wb, filename)
}
